### ISSUE TITLE
与openai 服务器连接不上 出现403  该如何解决

### ISSUE THREAD

**Issue by qigang47** [jtsang4/claude-to-chatgpt#2]
2023-05-16 02:34:22 INFO:     Started server process [1]
2023-05-16 02:34:22 INFO:     Waiting for application startup.
2023-05-16 02:34:22 INFO:     Application startup complete.
2023-05-16 02:34:22 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023-05-16 02:36:50 ERROR:    Exception in ASGI application
2023-05-16 02:36:50 Traceback (most recent call last):
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-16 02:36:50     result = await app(  # type: ignore[func-returns-value]
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-16 02:36:50     return await self.app(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-16 02:36:50     await super().__call__(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
2023-05-16 02:36:50     await self.middleware_stack(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-16 02:36:50     raise exc
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-16 02:36:50     await self.app(scope, receive, _send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
2023-05-16 02:36:50     await self.app(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-16 02:36:50     raise exc
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-16 02:36:50     await self.app(scope, receive, sender)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-16 02:36:50     raise e
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-16 02:36:50     await self.app(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
2023-05-16 02:36:50     await route.handle(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
2023-05-16 02:36:50     await self.app(scope, receive, send)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
2023-05-16 02:36:50     response = await func(request)
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
2023-05-16 02:36:50     raw_response = await run_endpoint_function(
2023-05-16 02:36:50   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-16 02:36:50     return await dependant.call(**values)
2023-05-16 02:36:50   File "/app/claude_to_chatgpt/app.py", line 49, in chat
2023-05-16 02:36:50     openai_response = await response.__anext__()
2023-05-16 02:36:50   File "/app/claude_to_chatgpt/adapter.py", line 145, in chat
2023-05-16 02:36:50     raise Exception(f"Error: {response.status_code}")
2023-05-16 02:36:50 Exception: Error: 403
2023-05-16 03:03:12 ERROR:    Exception in ASGI application
2023-05-16 03:03:12 Traceback (most recent call last):
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-16 03:03:12     result = await app(  # type: ignore[func-returns-value]
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-16 03:03:12     return await self.app(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-16 03:03:12     await super().__call__(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
2023-05-16 03:03:12     await self.middleware_stack(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-16 03:03:12     raise exc
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-16 02:36:50 INFO:     172.17.0.1:59252 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2023-05-16 03:00:36 INFO:     172.17.0.1:42472 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed
2023-05-16 03:00:36 INFO:     172.17.0.1:42472 - "GET /favicon.ico HTTP/1.1" 404 Not Found
2023-05-16 03:03:12 INFO:     172.17.0.1:56096 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2023-05-16 03:06:19 INFO:     172.17.0.1:41780 - "GET / HTTP/1.1" 404 Not Found
2023-05-16 03:03:12     await self.app(scope, receive, _send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
2023-05-16 03:03:12     await self.app(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-16 03:03:12     raise exc
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-16 03:03:12     await self.app(scope, receive, sender)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-16 03:03:12     raise e
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-16 03:03:12     await self.app(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
2023-05-16 03:03:12     await route.handle(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
2023-05-16 03:03:12     await self.app(scope, receive, send)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
2023-05-16 03:03:12     response = await func(request)
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
2023-05-16 03:03:12     raw_response = await run_endpoint_function(
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-16 03:03:12     return await dependant.call(**values)
2023-05-16 03:03:12   File "/app/claude_to_chatgpt/app.py", line 35, in chat
2023-05-16 03:03:12     openai_params = await request.json()
2023-05-16 03:03:12   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/requests.py", line 244, in json
2023-05-16 03:03:12     self._json = json.loads(body)
2023-05-16 03:03:12   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
2023-05-16 03:03:12     return _default_decoder.decode(s)
2023-05-16 03:03:12   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2023-05-16 03:03:12     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-05-16 03:03:12   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2023-05-16 03:03:12     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-05-16 03:03:12 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by qigang47** [comment]
curl 测试时出现Internal Server Error%

**Comment by qigang47** [comment]
是ip 的问题么 别的我都正常使用

**Comment by jtsang4** [comment]
> 2023-05-16 02:36:50 raise Exception(f"Error: {response.status_code}")
> 2023-05-16 02:36:50 Exception: Error: 403

报错 403，估计是 API key 不对

**Comment by qigang47** [comment]
> 
我的api 没啥问题 如果我不用docker 一切正常

**Comment by jtsang4** [comment]
> > 
> 
> 我的api 没啥问题 如果我不用docker 一切正常

我在本地测试了下最新版镜像，无法复现你的问题。可能真像你说的是 IP 问题，不过这也挺奇怪，因为我了解 Anthropic 没有限制 IP。你可以本地抓包调试看看

**Comment by jtsang4** [comment]
> > 
> 
> 我的api 没啥问题 如果我不用docker 一切正常

另外你可以试试参数加上 `stream` 为 `true`，看流式调用还会出现这个问题吗

**Comment by qigang47** [comment]
> > > 
> > 
> > 
> > 我的api 没啥问题 如果我不用docker 一切正常
> 
> 另外你可以试试参数加上 `stream` 为 `true`，看流式调用还会出现这个问题吗

问题已经解决 谢谢您的解答

**Comment by qigang47** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我的api 没啥问题 如果我不用docker 一切正常
> > > 
> > > 
> > > 另外你可以试试参数加上 `stream` 为 `true`，看流式调用还会出现这个问题吗
> > 
> > 
> > 问题已经解决 谢谢您的解答
> 
> 是流式调用以后问题就好了吗

是我的api 的问题 不好意思 呜呜呜

**Comment by jtsang4** [comment]
> 

哈哈，那 issue 我关了 😄
