### ISSUE TITLE
请求返回401

### ISSUE THREAD

**Issue by DMC-HYX** [jtsang4/claude-to-chatgpt#20]
Attaching to claude-to-chatgpt
claude-to-chatgpt  | INFO:     Started server process [1]
claude-to-chatgpt  | INFO:     Waiting for application startup.
claude-to-chatgpt  | INFO:     Application startup complete.
claude-to-chatgpt  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
claude-to-chatgpt  | INFO:     172.31.0.1:40810 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
claude-to-chatgpt  | ERROR:    Exception in ASGI application
claude-to-chatgpt  | Traceback (most recent call last):
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
claude-to-chatgpt  |     result = await app(  # type: ignore[func-returns-value]
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
claude-to-chatgpt  |     return await self.app(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
claude-to-chatgpt  |     await super().__call__(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
claude-to-chatgpt  |     await self.middleware_stack(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
claude-to-chatgpt  |     raise exc
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
claude-to-chatgpt  |     await self.app(scope, receive, _send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
claude-to-chatgpt  |     await self.app(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
claude-to-chatgpt  |     raise exc
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
claude-to-chatgpt  |     await self.app(scope, receive, sender)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
claude-to-chatgpt  |     raise e
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
claude-to-chatgpt  |     await self.app(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
claude-to-chatgpt  |     await route.handle(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
claude-to-chatgpt  |     await self.app(scope, receive, send)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
claude-to-chatgpt  |     response = await func(request)
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
claude-to-chatgpt  |     raw_response = await run_endpoint_function(
claude-to-chatgpt  |   File "/root/.cache/pypoetry/virtualenvs/claude-to-chatgpt-9TtSrW0h-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
claude-to-chatgpt  |     return await dependant.call(**values)
claude-to-chatgpt  |   File "/app/claude_to_chatgpt/app.py", line 49, in chat
claude-to-chatgpt  |     openai_response = await response.__anext__()
claude-to-chatgpt  |   File "/app/claude_to_chatgpt/adapter.py", line 148, in chat
claude-to-chatgpt  |     raise Exception(f"Error: {response.status_code}")
claude-to-chatgpt  | Exception: Error: 401

**Comment by caicai1998** [comment]
同样遇到该问题
